### PR TITLE
added external syslog server

### PR DESCRIPTION
**Pull request by moonbuggy**
I still don't know how to work Git properly. I thought I could modify files in [your pull request](https://github.com/moonbuggy/docker-hostdns/pull/2), but I'm not sure how and gave up trying to figure it out. :)

I added some arguments to allow an external syslog server, rather than be locked to ``/dev/log``. This seems to work on my setup.

### CODE REVIEW

**Comment by moonbuggy** [comment]
The reason I'm not sure if this is useful or if it's just bloat, btw, is because I'm still playing with my syslog setup and I'm not sure exactly how it's going to end up. From the container I can log via Docker anyway, but the syslog on the host is setup to feed messages back to syslog-ng running in a container. It seemed sensible to have the option to go directly from one container to another and bypass the host.

I don't know what typical use cases would be because I don't really know how other people normally handle logging for containers.

The two arguments could be compressed into a single argument, accepting a string of the form ``(udp|tcp)://<host>[:<port>]``. I didn't do it this way because I'm not hugely proficient in Python and I assumed I'd probably be unable to parse the string in the best/most efficient manner.

**Comment by glorpen** [comment]
About syslog arguments - my thoughts exactly :)
If you don't feel adventurous about python code I can add this feature, is it fine with you?

**Comment by moonbuggy** [comment]
I didn't want to be adventurous with code that I thought you might want to merge. :) I assumed I'd end up importing unnecessary string handling/parsing modules (it seems easy enough to do with urllib.parse) because I'd be unaware of other ways to do it, and I thought avoiding unnecessary imports made sense for something that's going to end up in a container.

If you want it done with urllib.parse I'm happy to do it, but if you know a better way you'd prefer then I'll leave it to you to implement. Either is fine by me.

**Comment by moonbuggy** [comment]
You could just leave it as two separate arguments, btw. Or not merge it at all. I didn't mean to create extra work for you by declaring "here's something I've half-implemented, make it better".

If it's easier for you I should have a chance next week to properly look into it and find an efficient way to do it without importing any modules, I just don't have the time today to learn new things.

Really, I'm happy with whatever you want to do or not do with this PR.

**Comment by glorpen** [comment]
No worries, I'll happily implement this feature. Also I didn't read your response as "here, now make it better" so no need to feel sorry/apologetic :)
I just didn't want to take away making implementation from you if you wanted to do it (and then I could be "change it here and here" ;) )

**Comment by glorpen** [comment]
I've created branch https://github.com/glorpen/docker-hostdns/tree/syslog . I'll update readme and maybe add some tests later, but for now code should work, with BC and tcp/udp/unix schemas.

**Comment by moonbuggy** [comment]
Oh, so it looks like using urllib was the right way to go after all? Maybe I'm more proficient in Python than I thought. :)

You implementation seems to work in my setup. (I only tested ``udp://<host>:<port>``,  but if it parses that it should pass other options.) 

I've merged it with this branch and updated the README. One less thing for you to do, I figured.

**Comment by glorpen** [comment]
Yes, urllib... at first I thought about using some regex since its a simple string but then as you pointed out, there is already urllib.parse and it works just right :)

Thanks for changes in README, could you clean & rebase your commits onto branch `syslog`? So there is no commits that are already overwritten (like syslog option handling).
I'm happy to help with git-fu if you need it :)

**Comment by moonbuggy** [comment]
That's kind of funny. I was thinking you might prefer to do it with a regex or something. :) I was weighing up the trade-off between slightly increased image size and potentially inefficient/messy code, since I've not spent a lot of time directly splitting/pattern matching strings in python before. :) Probably just overthinking it.

If you don't mind bringing your Git-Fu skills in to play, letting me know what to do guarantees I do what you want. :) I'm still figuring it all out.

At the moment I'm assuming something like this is what needs to be done, but I wouldn't be surprised if I'm wildly mistaken:

``git remote add glorpen https://github.com/glorpen/docker-hostdns.git``
``git checkout pull_2``
``git rebase -i remotes/syslog/pull_2``

**Comment by glorpen** [comment]
Hah :D I think regex would be faster (in executing) but then urllib is included in python distribution and we are using it in cli script which is executed only once. So choice for me would be "slight one time boost where it is not required" vs. "developer sanity" ;) as regex simple as it could be is still a regex.

Your Git-Fu should work, I would be lazy and used git commit id instead of adding glorpen to remotes :) (also, it should be then `git rebase -i remotes/glorpen/syslog`)
`git checkout pull_2`
`git rebase -i da51dbac275c5739a07a032b5f2cab3290f2ece2` (last commit from branch syslog)
drop & pick & resolve conflicts as needed
`git push --force` to replace changes on github

**Comment by moonbuggy** [comment]
Thanks for the help. 

I think I've done what you wanted..? The diff on this PR showed only the README differed from what you have committed upstream, so that's the only thing I picked. 

It probably took you longer to explain the Git commands than it would have to do the README change yourself. :) Sorry, but thanks again.

**Comment by glorpen** [comment]
Thanks. Yes, I think now this PR looks as it should. I'll merge & update master soon-ish.

As for git, commands and stuff, no problem, happy to help :)

**Pull request merged**
